/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * <p>DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.apache.hive.service.rpc.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(
    value = "Autogenerated by Thrift Compiler (0.19.0)",
    date = "2024-02-23")
public class TGetResultSetMetadataReq
    implements org.apache.thrift.TBase<TGetResultSetMetadataReq, TGetResultSetMetadataReq._Fields>,
        java.io.Serializable,
        Cloneable,
        Comparable<TGetResultSetMetadataReq> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC =
      new org.apache.thrift.protocol.TStruct("TGetResultSetMetadataReq");

  private static final org.apache.thrift.protocol.TField OPERATION_HANDLE_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "operationHandle", org.apache.thrift.protocol.TType.STRUCT, (short) 1);
  private static final org.apache.thrift.protocol.TField INCLUDE_CLOUD_RESULT_FILES_FIELD_DESC =
      new org.apache.thrift.protocol.TField(
          "includeCloudResultFiles", org.apache.thrift.protocol.TType.BOOL, (short) 3329);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
      new TGetResultSetMetadataReqStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
      new TGetResultSetMetadataReqTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable TOperationHandle operationHandle; // required
  public boolean includeCloudResultFiles; // optional

  /**
   * The set of fields this struct contains, along with convenience methods for finding and
   * manipulating them.
   */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPERATION_HANDLE((short) 1, "operationHandle"),
    INCLUDE_CLOUD_RESULT_FILES((short) 3329, "includeCloudResultFiles");

    private static final java.util.Map<java.lang.String, _Fields> byName =
        new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /** Find the _Fields constant that matches fieldId, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch (fieldId) {
        case 1: // OPERATION_HANDLE
          return OPERATION_HANDLE;
        case 3329: // INCLUDE_CLOUD_RESULT_FILES
          return INCLUDE_CLOUD_RESULT_FILES;
        default:
          return null;
      }
    }

    /** Find the _Fields constant that matches fieldId, throwing an exception if it is not found. */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null)
        throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /** Find the _Fields constant that matches name, or null if its not found. */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INCLUDECLOUDRESULTFILES_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.INCLUDE_CLOUD_RESULT_FILES};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap =
        new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(
        _Fields.OPERATION_HANDLE,
        new org.apache.thrift.meta_data.FieldMetaData(
            "operationHandle",
            org.apache.thrift.TFieldRequirementType.REQUIRED,
            new org.apache.thrift.meta_data.StructMetaData(
                org.apache.thrift.protocol.TType.STRUCT, TOperationHandle.class)));
    tmpMap.put(
        _Fields.INCLUDE_CLOUD_RESULT_FILES,
        new org.apache.thrift.meta_data.FieldMetaData(
            "includeCloudResultFiles",
            org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.FieldValueMetaData(
                org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(
        TGetResultSetMetadataReq.class, metaDataMap);
  }

  public TGetResultSetMetadataReq() {}

  public TGetResultSetMetadataReq(TOperationHandle operationHandle) {
    this();
    this.operationHandle = operationHandle;
  }

  /** Performs a deep copy on <i>other</i>. */
  public TGetResultSetMetadataReq(TGetResultSetMetadataReq other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetOperationHandle()) {
      this.operationHandle = new TOperationHandle(other.operationHandle);
    }
    this.includeCloudResultFiles = other.includeCloudResultFiles;
  }

  @Override
  public TGetResultSetMetadataReq deepCopy() {
    return new TGetResultSetMetadataReq(this);
  }

  @Override
  public void clear() {
    this.operationHandle = null;
    setIncludeCloudResultFilesIsSet(false);
    this.includeCloudResultFiles = false;
  }

  @org.apache.thrift.annotation.Nullable
  public TOperationHandle getOperationHandle() {
    return this.operationHandle;
  }

  public TGetResultSetMetadataReq setOperationHandle(
      @org.apache.thrift.annotation.Nullable TOperationHandle operationHandle) {
    this.operationHandle = operationHandle;
    return this;
  }

  public void unsetOperationHandle() {
    this.operationHandle = null;
  }

  /**
   * Returns true if field operationHandle is set (has been assigned a value) and false otherwise
   */
  public boolean isSetOperationHandle() {
    return this.operationHandle != null;
  }

  public void setOperationHandleIsSet(boolean value) {
    if (!value) {
      this.operationHandle = null;
    }
  }

  public boolean isIncludeCloudResultFiles() {
    return this.includeCloudResultFiles;
  }

  public TGetResultSetMetadataReq setIncludeCloudResultFiles(boolean includeCloudResultFiles) {
    this.includeCloudResultFiles = includeCloudResultFiles;
    setIncludeCloudResultFilesIsSet(true);
    return this;
  }

  public void unsetIncludeCloudResultFiles() {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.clearBit(
            __isset_bitfield, __INCLUDECLOUDRESULTFILES_ISSET_ID);
  }

  /**
   * Returns true if field includeCloudResultFiles is set (has been assigned a value) and false
   * otherwise
   */
  public boolean isSetIncludeCloudResultFiles() {
    return org.apache.thrift.EncodingUtils.testBit(
        __isset_bitfield, __INCLUDECLOUDRESULTFILES_ISSET_ID);
  }

  public void setIncludeCloudResultFilesIsSet(boolean value) {
    __isset_bitfield =
        org.apache.thrift.EncodingUtils.setBit(
            __isset_bitfield, __INCLUDECLOUDRESULTFILES_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(
      _Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
      case OPERATION_HANDLE:
        if (value == null) {
          unsetOperationHandle();
        } else {
          setOperationHandle((TOperationHandle) value);
        }
        break;

      case INCLUDE_CLOUD_RESULT_FILES:
        if (value == null) {
          unsetIncludeCloudResultFiles();
        } else {
          setIncludeCloudResultFiles((java.lang.Boolean) value);
        }
        break;
    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
      case OPERATION_HANDLE:
        return getOperationHandle();

      case INCLUDE_CLOUD_RESULT_FILES:
        return isIncludeCloudResultFiles();
    }
    throw new java.lang.IllegalStateException();
  }

  /**
   * Returns true if field corresponding to fieldID is set (has been assigned a value) and false
   * otherwise
   */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
      case OPERATION_HANDLE:
        return isSetOperationHandle();
      case INCLUDE_CLOUD_RESULT_FILES:
        return isSetIncludeCloudResultFiles();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TGetResultSetMetadataReq)
      return this.equals((TGetResultSetMetadataReq) that);
    return false;
  }

  public boolean equals(TGetResultSetMetadataReq that) {
    if (that == null) return false;
    if (this == that) return true;

    boolean this_present_operationHandle = true && this.isSetOperationHandle();
    boolean that_present_operationHandle = true && that.isSetOperationHandle();
    if (this_present_operationHandle || that_present_operationHandle) {
      if (!(this_present_operationHandle && that_present_operationHandle)) return false;
      if (!this.operationHandle.equals(that.operationHandle)) return false;
    }

    boolean this_present_includeCloudResultFiles = true && this.isSetIncludeCloudResultFiles();
    boolean that_present_includeCloudResultFiles = true && that.isSetIncludeCloudResultFiles();
    if (this_present_includeCloudResultFiles || that_present_includeCloudResultFiles) {
      if (!(this_present_includeCloudResultFiles && that_present_includeCloudResultFiles))
        return false;
      if (this.includeCloudResultFiles != that.includeCloudResultFiles) return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetOperationHandle()) ? 131071 : 524287);
    if (isSetOperationHandle()) hashCode = hashCode * 8191 + operationHandle.hashCode();

    hashCode = hashCode * 8191 + ((isSetIncludeCloudResultFiles()) ? 131071 : 524287);
    if (isSetIncludeCloudResultFiles())
      hashCode = hashCode * 8191 + ((includeCloudResultFiles) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(TGetResultSetMetadataReq other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison =
        java.lang.Boolean.compare(isSetOperationHandle(), other.isSetOperationHandle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperationHandle()) {
      lastComparison =
          org.apache.thrift.TBaseHelper.compareTo(this.operationHandle, other.operationHandle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison =
        java.lang.Boolean.compare(
            isSetIncludeCloudResultFiles(), other.isSetIncludeCloudResultFiles());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIncludeCloudResultFiles()) {
      lastComparison =
          org.apache.thrift.TBaseHelper.compareTo(
              this.includeCloudResultFiles, other.includeCloudResultFiles);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot)
      throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TGetResultSetMetadataReq(");
    boolean first = true;

    sb.append("operationHandle:");
    if (this.operationHandle == null) {
      sb.append("null");
    } else {
      sb.append(this.operationHandle);
    }
    first = false;
    if (isSetIncludeCloudResultFiles()) {
      if (!first) sb.append(", ");
      sb.append("includeCloudResultFiles:");
      sb.append(this.includeCloudResultFiles);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (operationHandle == null) {
      throw new org.apache.thrift.protocol.TProtocolException(
          "Required field 'operationHandle' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (operationHandle != null) {
      operationHandle.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in)
      throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and
      // doesn't call the default constructor.
      __isset_bitfield = 0;
      read(
          new org.apache.thrift.protocol.TCompactProtocol(
              new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TGetResultSetMetadataReqStandardSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TGetResultSetMetadataReqStandardScheme getScheme() {
      return new TGetResultSetMetadataReqStandardScheme();
    }
  }

  private static class TGetResultSetMetadataReqStandardScheme
      extends org.apache.thrift.scheme.StandardScheme<TGetResultSetMetadataReq> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TGetResultSetMetadataReq struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true) {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // OPERATION_HANDLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operationHandle = new TOperationHandle();
              struct.operationHandle.read(iprot);
              struct.setOperationHandleIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3329: // INCLUDE_CLOUD_RESULT_FILES
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.includeCloudResultFiles = iprot.readBool();
              struct.setIncludeCloudResultFilesIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TGetResultSetMetadataReq struct)
        throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.operationHandle != null) {
        oprot.writeFieldBegin(OPERATION_HANDLE_FIELD_DESC);
        struct.operationHandle.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIncludeCloudResultFiles()) {
        oprot.writeFieldBegin(INCLUDE_CLOUD_RESULT_FILES_FIELD_DESC);
        oprot.writeBool(struct.includeCloudResultFiles);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
  }

  private static class TGetResultSetMetadataReqTupleSchemeFactory
      implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TGetResultSetMetadataReqTupleScheme getScheme() {
      return new TGetResultSetMetadataReqTupleScheme();
    }
  }

  private static class TGetResultSetMetadataReqTupleScheme
      extends org.apache.thrift.scheme.TupleScheme<TGetResultSetMetadataReq> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TGetResultSetMetadataReq struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.operationHandle.write(oprot);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIncludeCloudResultFiles()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetIncludeCloudResultFiles()) {
        oprot.writeBool(struct.includeCloudResultFiles);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TGetResultSetMetadataReq struct)
        throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot =
          (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.operationHandle = new TOperationHandle();
      struct.operationHandle.read(iprot);
      struct.setOperationHandleIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.includeCloudResultFiles = iprot.readBool();
        struct.setIncludeCloudResultFilesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(
      org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme())
            ? STANDARD_SCHEME_FACTORY
            : TUPLE_SCHEME_FACTORY)
        .getScheme();
  }
}
