package com.databricks.jdbc.commons;

public enum MetricsList {
  LIST_CATALOGS_METADATA_SEA,
  LIST_SCHEMAS_METADATA_SEA,
  LIST_TABLES_METADATA_SEA,
  LIST_COLUMNS_METADATA_SEA,
  LIST_TABLE_TYPES_METADATA_SEA,
  LIST_FUNCTIONS_METADATA_SEA,
  LIST_PRIMARY_KEYS_METADATA_SEA,
  RECORD_METRICS_ERROR_COUNT,
  CREATE_SESSION_THRIFT,
}
