<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.databricks</groupId>
    <artifactId>databricks-jdbc-parent</artifactId>
    <version>3.4.2</version>
  </parent>

  <artifactId>test-databricks-jdbc-uber</artifactId>
  <packaging>jar</packaging>
  <name>Test Uber</name>
  <description>Test JDBC databricks driver uber jar.</description>

  <properties>
    <!-- Test module - should not be deployed to Maven Central -->
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.databricks</groupId>
      <artifactId>databricks-jdbc</artifactId>
      <version>3.4.2</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.jupiter.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>